version: '3.5'

services:
  db:
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres_flow
    image: postgres:14.3-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'
