version: '3.5'

services:
  postgres:
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    image: postgres:14.3-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5434:5432'
